### ISSUE TITLE
ports with missing physical network cause inspection to fail

### ISSUE THREAD

**Issue by jovial** [stackhpc/stackhpc-inspector-plugins#7]
Given a port like:
```
+-----------------------+--------------------------------------+
| Field                 | Value                                |
+-----------------------+--------------------------------------+
| address               | 18:03:73:ff:96:8d                    |
| created_at            | 2018-07-30T09:27:26+00:00            |
| extra                 | {}                                   |
| internal_info         | {}                                   |
| local_link_connection | {}                                   |
| node_uuid             | b111570e-e560-400d-a0ce-a180f10d3b7a |
| physical_network      | None                                 |
| portgroup_uuid        | None                                 |
| pxe_enabled           | False                                |
| updated_at            | None                                 |
| uuid                  | 13e0cfb7-51df-4a0a-9aa0-816f793b850e |
+-----------------------+--------------------------------------+
```

you will see an error like: 
```
2018-08-03 09:52:24.873 7 ERROR ironic_inspector.node_cache [req-c439f719-34cc-4a9a-baf1-10785a6cd2b4 - - - - -] [node: b31e62f9-0823-46c5-9575-746e285e6706 state processing] Processing the error event because of an exception <type 'exceptions.AttributeError'>: id raised by ironic_inspector.process._process_node
2018-08-03 09:52:24.874 7 INFO ironic_inspector.node_cache [req-c439f719-34cc-4a9a-baf1-10785a6cd2b4 - - - - -] [node: b31e62f9-0823-46c5-9575-746e285e6706 state processing] Updating node state: processing --> error
2018-08-03 09:52:25.035 7 ERROR ironic_inspector.process [req-c439f719-34cc-4a9a-baf1-10785a6cd2b4 - - - - -] Unexpected exception during processing: AttributeError: id
2018-08-03 09:52:25.035 7 ERROR ironic_inspector.process Traceback (most recent call last):
2018-08-03 09:52:25.035 7 ERROR ironic_inspector.process   File "/usr/lib/python2.7/site-packages/ironic_inspector/process.py", line 235, in process
2018-08-03 09:52:25.035 7 ERROR ironic_inspector.process     result = _process_node(node_info, node, introspection_data)
2018-08-03 09:52:25.035 7 ERROR ironic_inspector.process   File "/usr/lib/python2.7/site-packages/ironic_inspector/node_cache.py", line 579, in inner
2018-08-03 09:52:25.035 7 ERROR ironic_inspector.process     return func(node_info, *args, **kwargs)
2018-08-03 09:52:25.035 7 ERROR ironic_inspector.process   File "/usr/lib/python2.7/site-packages/ironic_inspector/node_cache.py", line 557, in inner
2018-08-03 09:52:25.035 7 ERROR ironic_inspector.process     node_info.finished(istate.Events.error, error=str(exc))
2018-08-03 09:52:25.035 7 ERROR ironic_inspector.process   File "/usr/lib/python2.7/site-packages/oslo_utils/excutils.py", line 220, in __exit__
2018-08-03 09:52:25.035 7 ERROR ironic_inspector.process     self.force_reraise()
2018-08-03 09:52:25.035 7 ERROR ironic_inspector.process   File "/usr/lib/python2.7/site-packages/oslo_utils/excutils.py", line 196, in force_reraise
2018-08-03 09:52:25.035 7 ERROR ironic_inspector.process     six.reraise(self.type_, self.value, self.tb)
2018-08-03 09:52:25.035 7 ERROR ironic_inspector.process   File "/usr/lib/python2.7/site-packages/ironic_inspector/node_cache.py", line 541, in inner
2018-08-03 09:52:25.035 7 ERROR ironic_inspector.process     ret = func(node_info, *args, **kwargs)
2018-08-03 09:52:25.035 7 ERROR ironic_inspector.process   File "/usr/lib/python2.7/site-packages/ironic_inspector/process.py", line 268, in _process_node
2018-08-03 09:52:25.035 7 ERROR ironic_inspector.process     _run_post_hooks(node_info, introspection_data)
2018-08-03 09:52:25.035 7 ERROR ironic_inspector.process   File "/usr/lib/python2.7/site-packages/ironic_inspector/process.py", line 261, in _run_post_hooks
2018-08-03 09:52:25.035 7 ERROR ironic_inspector.process     hook_ext.obj.before_update(introspection_data, node_info)
2018-08-03 09:52:25.035 7 ERROR ironic_inspector.process   File "/usr/lib/python2.7/site-packages/stackhpc_inspector_plugins/plugins/base_physnet.py", line 104, in before_update
2018-08-03 09:52:25.035 7 ERROR ironic_inspector.process     patch = self._get_physnet_patch(physnet, port)
2018-08-03 09:52:25.035 7 ERROR ironic_inspector.process   File "/usr/lib/python2.7/site-packages/stackhpc_inspector_plugins/plugins/base_physnet.py", line 62, in _get_physnet_patch
2018-08-03 09:52:25.035 7 ERROR ironic_inspector.process     port.physical_network == physnet):
2018-08-03 09:52:25.035 7 ERROR ironic_inspector.process   File "/usr/lib/python2.7/site-packages/ironicclient/common/apiclient/base.py", line 478, in __getattr__
2018-08-03 09:52:25.035 7 ERROR ironic_inspector.process     self.get()
2018-08-03 09:52:25.035 7 ERROR ironic_inspector.process   File "/usr/lib/python2.7/site-packages/ironicclient/common/apiclient/base.py", line 496, in get
2018-08-03 09:52:25.035 7 ERROR ironic_inspector.process     new = self.manager.get(self.id)
2018-08-03 09:52:25.035 7 ERROR ironic_inspector.process   File "/usr/lib/python2.7/site-packages/ironicclient/common/apiclient/base.py", line 481, in __getattr__
2018-08-03 09:52:25.035 7 ERROR ironic_inspector.process     raise AttributeError(k)
2018-08-03 09:52:25.035 7 ERROR ironic_inspector.process AttributeError: id
2018-08-03 09:52:25.035 7 ERROR ironic_inspector.process 
2018-08-03 09:52:25.140 7 INFO ironic_inspector.process [req-c439f719-34cc-4a9a-baf1-10785a6cd2b4 - - - - -] [node: b31e62f9-0823-46c5-9575-746e285e6706 state error MAC 18:03:73:ff:6b:83 BMC 10.68.3.54] Ramdisk logs were stored in file b31e62f9-0823-46c5-9575-746e285e6706_20180803-085225.140195.tar.gz
2018-08-03 09:52:25.141 7 ERROR ironic_inspector.utils [req-c439f719-34cc-4a9a-baf1-10785a6cd2b4 - - - - -] [node: b31e62f9-0823-46c5-9575-746e285e6706 state error MAC 18:03:73:ff:6b:83 BMC 10.68.3.54] Unexpected exception AttributeError during processing: id
```
in inspector logs.

**Comment by markgoddard** [comment]
I'd be surprised if this always fails without physnets applied since we have some ports without physnets, but perhaps we missed it.

**Comment by markgoddard** [comment]
It looks like it's trying to lazily load the physical_network attribute. It does this by GETting a port via the API using the object's id attribute, but the id attribute is not present.

**Comment by markgoddard** [comment]
This doesn't happen every time - it just happened on 16 out of 80 concurrent inspections.

**Comment by markgoddard** [comment]
Also saw it during a `openstack baremetal introspection reprocess <node>`. It didn't happen on a second reprocess though.

**Comment by markgoddard** [comment]
Managed to grab some debug info. The plugin is doing a port list, since the node cache ports do not have a physical_network field. This is expected. Here is the list of ports returned:

```
<Port {u'local_link_connection': {u'switch_info': u'ethsw-dr05-u2
2', u'port_id': u'gi1/0/24', u'switch_id': u'f8:b1:56:01:27:db'}, u'node_uuid': u'1f5245e8-b425-4d4f-a2db-a0f6cc434944', u'uuid': u'6c58779d-698d-451d-825d-b6999434ee7a', u'links': [{u'href': u'http://10.
65.0.1:6385/v1/ports/6c58779d-698d-451d-825d-b6999434ee7a', u'rel': u'self'}, {u'href': u'http://10.65.0.1:6385/ports/6c58779d-698d-451d-825d-b6999434ee7a', u'rel': u'bookmark'}], u'extra': {}, u'pxe_enab
led': True, u'portgroup_uuid': None, u'updated_at': u'2018-08-14T13:51:47+00:00', u'physical_network': u'physnet1', u'address': u'18:03:73:ff:86:96', u'internal_info': {}, u'created_at': u'2018-08-13T16:4
5:52+00:00'}>

<Port {u'local_link_connection': {}, u'node_uuid': u'1f5245e8-b425-4d4f-a2db-a0f6cc434944', u'uuid': u'2036b3d6-cf14-4056-893d-16dbb0985240', u'links': [{u'href': u'http://10.65.0.1:6385/v1
/ports/2036b3d6-cf14-4056-893d-16dbb0985240', u'rel': u'self'}, {u'href': u'http://10.65.0.1:6385/ports/2036b3d6-cf14-4056-893d-16dbb0985240', u'rel': u'bookmark'}], u'extra': {}, u'pxe_enabled': False, u
'created_at': u'2018-08-13T16:45:52+00:00', u'updated_at': None, u'address': u'18:03:73:ff:86:97', u'internal_info': {}}>

<Port {u'local_link_connection': {}, u'node_uuid': u'1f5245e8-b425-4d4f-a2db-a0f6
cc434944', u'uuid': u'a831b9c2-0901-4a57-9a6b-7e761c7944f3', u'links': [{u'href': u'http://10.65.0.1:6385/v1/ports/a831b9c2-0901-4a57-9a6b-7e761c7944f3', u'rel': u'self'}, {u'href': u'http://10.65.0.1:638
5/ports/a831b9c2-0901-4a57-9a6b-7e761c7944f3', u'rel': u'bookmark'}], u'extra': {u'client-id': u'ff:00:00:00:00:00:02:00:00:02:c9:00:00:02:c9:03:00:34:bb:b1'}, u'pxe_enabled': False, u'created_at': u'2018
-08-13T16:45:52+00:00', u'updated_at': u'2018-08-13T16:45:54+00:00', u'address': u'00:02:c9:34:bb:b1', u'internal_info': {}}>
```

Note that only the first port has a physical_network field, and none has an 'id' field.

**Comment by markgoddard** [comment]
Bizarrely, in a working case the object claim to be Nodes:

```
<Node {u'local_link_connection': {}, u'node_uuid': u'e2566354-656c-4e1d-a7cc-1225cdc39773', u'uuid': u'87602756-ac7e-494f-b6cf-7ce6ab47d4cc', u'links': [{u'href': u'http://10.65.0.1:6385/v1/ports/87602756-ac7e-494f-b6cf-7ce6ab47d4cc', u'rel': u'self'}, {u'href': u'http://10.65.0.1:6385/ports/87602756-ac7e-494f-b6cf-7ce6ab47d4cc', u'rel': u'bookmark'}], u'extra': {u'client-id': u'ff:00:00:00:00:00:02:00:00:02:c9:00:00:02:c9:03:00:35:60:61'}, u'pxe_enabled': False, u'portgroup_uuid': None, u'updated_at': u'2018-08-13T16:30:23+00:00', u'physical_network': u'physnet3', u'address': u'00:02:c9:35:60:61', u'internal_info': {}, u'created_at': u'2018-08-13T16:30:21+00:00'}>

<Node {u'local_link_connection': {u'switch_info': u'ethsw-dr06-u22', u'port_id': u'gi1/0/30', u'switch_id': u'5c:26:0a:ea:41:fd'}, u'node_uuid': u'e2566354-656c-4e1d-a7cc-1225cdc39773', u'uuid': u'f3a9937f-aa53-4135-b631-2cc898f15c56', u'links': [{u'href': u'http://10.65.0.1:6385/v1/ports/f3a9937f-aa53-4135-b631-2cc898f15c56', u'rel': u'self'}, {u'href': u'http://10.65.0.1:6385/ports/f3a9937f-aa53-4135-b631-2cc898f15c56', u'rel': u'bookmark'}], u'extra': {}, u'pxe_enabled': True, u'portgroup_uuid': None, u'updated_at': u'2018-08-14T10:36:03+00:00', u'physical_network': u'physnet1', u'address': u'18:03:73:ff:7a:51', u'internal_info': {}, u'created_at': u'2018-08-13T16:30:21+00:00'}>

<Node {u'local_link_connection': {}, u'node_uuid': u'e2566354-656c-4e1d-a7cc-1225cdc39773', u'uuid': u'cc23f93a-1572-4f4c-92f7-20fc1fa50de0', u'links': [{u'href': u'http://10.65.0.1:6385/v1/ports/cc23f93a-1572-4f4c-92f7-20fc1fa50de0', u'rel': u'self'}, {u'href': u'http://10.65.0.1:6385/ports/cc23f93a-1572-4f4c-92f7-20fc1fa50de0', u'rel': u'bookmark'}], u'extra': {}, u'pxe_enabled': False, u'portgroup_uuid': None, u'updated_at': None, u'physical_network': None, u'address': u'18:03:73:ff:7a:52', u'internal_info': {}, u'created_at': u'2018-08-13T16:30:21+00:00'}>
```

**Comment by markgoddard** [comment]
The Port/Node failing/working pattern appears consistent.

**Comment by markgoddard** [comment]
Seems to be happening when the plugin uses the port list in the node cache. If the first port has a physical_network field but any others do not, we will hit this. Need to check all ports.

**Comment by markgoddard** [comment]
Should be fixed via https://github.com/stackhpc/stackhpc-inspector-plugins/commit/449a0cae29a2034e12891011d47fd148ee2637d9.
